name: salesforce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  flutter_isolate: ^2.1.0
  dart_kafka:
    path: 'C:/Projetos/dart/dart-kafka'
  cron: ^0.6.2
  intl: ^0.20.2
  dio: ^5.8.0+1
  fluttertoast: ^8.2.12
  crypto: ^3.0.6
  flutter_svg: ^2.1.0
  persistent_bottom_nav_bar_v2: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/migrations/
    - assets/migrations/upgrades/
    - assets/migrations/downgrades/
